### ISSUE TITLE
Indexing issues

### ISSUE THREAD

**Issue by AsimIqbal2nd** [ejtaal/mr#3]
1. Lisaan ul Arab is returning -1 page i.e. previous page to required page. +1 required. 
2. MGF index still not matching images, you can check any image and title being shown e.g. on searching awl I am getting title as awl but image as axr
3. VI is also showing wrong search results, on searching awl, it is giving bda
4.  Al Munawwir is problem is same as Lisaan ul Arab problem.

**Comment by ejtaal** [comment]
Old issue, presumably now all fixed.
