### ISSUE TITLE
Swipe must be removed

### ISSUE THREAD

**Issue by AsimIqbal2nd** [ejtaal/mr#4]
The newly added swipe function is causing a lot of problems, when I try to touch screen and navigate down, it either opens previous page or next page. Even with extreme care to touch exact center of screen, still the next or previous page is opened. Swipe function must be removed, as I don't know how many people requested this function, but for such pages where screen has to be touched many times to navigate up and down, swipe will always be a failure.

**Comment by ejtaal** [comment]
I've adjusted the default page sensitivity and added an option in the menu to disable this function altogether should one wish to do so.
