### ISSUE TITLE
image problem in LQN

### ISSUE THREAD

**Issue by AsimIqbal2nd** [ejtaal/mr#5]
in Mawrid Reader, Lughaat ul-Quran (Urdu), page 770 (of 2139) image is cut off from the right side i.e. right column text is cut off from the right side few words cut off in each row.  
![lqn-0791](https://f.cloud.github.com/assets/5710509/1819243/fca31504-7078-11e3-8bae-91799ab0c29a.png)

**Comment by ejtaal** [comment]
I've uploaded your new images so this should be fixed?
