### ISSUE TITLE
Searching double letter roots

### ISSUE THREAD

**Issue by bilaljavaid** [ejtaal/mr#7]
If I am looking for the verb مَنَّ (meaning to be kind), I would search for the root م ن ن. However searching this root gives the result a few pages after what I would be looking for. I have to search just م ن to get the correct index.

Similar examples are the verbs صَدَّ and حَجَّ. If I search ص د د or ح ج ج it goes to the wrong page.

Let me know if this is an issue or is it supposed to work like that?

**Comment by ejtaal** [comment]
apologies for the late reply. This is actually dependent on how the books have indexed their headings. Some have been indexed according to the assuming the double letters are both written, whereas others assuming the doubled letter is only written once. I have to create the index in such a way that the search program is able to find the right page, as this assumes the index is completely alphabetical.
